#!/bin/bash

job_id=$1
job_name=$2
partition=$3
exit_code=$4
command=$SLURM_EXEC_COMMAND

url=$TEAMS_SLURM_WEBHOOK
if [ -z "$url" ]; then
    echo "Error: TEAMS_SLURM_WEBHOOK is not set"
    exit 1
fi

if [ "$exit_code" -eq 0 ]; then
    theme_color="0072C6" # blue
    title="✅ Job ($job_id: $job_name) is done ($partition)"
else
    theme_color="FF0000" # red
    title="❌ Job ($job_id: $job_name) is failed ($partition)"
fi
content="\`\`\`bash\n$command\n\`\`\`"

echo $title
echo $content

curl -X POST $url \
-H "Content-Type: application/json" \
-d '{
  "type": "message",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "contentUrl": null,
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.4",
        "body": [
          {
            "type": "TextBlock",
            "text": "'"$title"'",
            "weight": "Bolder",
            "size": "Medium"
          },
          {
            "type": "TextBlock",
            "text": "'"$content"'",
            "wrap": true,
            "fontType": "Monospace"
          }
        ]
      }
    }
  ]
}'
