#!/bin/bash

job_id=$1
job_name=$2
partition=$3
command=$SLURM_EXEC_COMMAND

url=$TEAMS_SLURM_WEBHOOK
if [ -z "$url" ]; then
    echo "Error: TEAMS_SLURM_WEBHOOK is not set"
    exit 1
fi

theme_color="C274E3"
title="🚀 Job ($job_id: $job_name) is started ($partition)"
content="\`\`\`bash\n$command\n\`\`\`"

echo $title
echo $content

curl -X POST $url \
-H "Content-Type: application/json" \
-d '{
  "type": "message",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "contentUrl": null,
      "content": {
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "type": "AdaptiveCard",
        "version": "1.4",
        "body": [
          {
            "type": "TextBlock",
            "text": "'"$title"'",
            "weight": "Bolder",
            "size": "Medium"
          },
          {
            "type": "TextBlock",
            "text": "'"$content"'",
            "wrap": true,
            "fontType": "Monospace"
          }
        ]
      }
    }
  ]
}'
